### PR TITLE
New options :wrap-in-main, :tangle-in-main and :auto-main

### PR DESCRIPTION
**Pull request by zzamboni**
If `:wrap-in-main` is true, then the code block is wrapped into a `bundle agent __main_` so that "bare snippets" can also be executed.

Example:

    #+begin_src cfengine3 :wrap-in-main yes
      reports:
        "Howdy";
    #+end_src

    #+RESULTS:
    #+begin_src console
    R: Howdy
    #+end_src

If `:tangle-in-main` is true, the same transformation is applied for tangling the file on output.

`:auto-main` is a shortcut for enabling both `:wrap-in-main` and `:tangle-in-main`.

Other changes:
- Better default for `:command-in-result-filename`: now defaults to the tangle output filename if specified, otherwise to the temp filename as before.
- Some internal cleanup by introducing new internal utility functions.

### CODE REVIEW

**Comment by nickanderson** [comment]
I have no objection to this. It's really nice for snippets that are not complete. Are you happy with how it is now?

**Comment by zzamboni** [comment]
I'm happy with it. The issue of tangling can be addressed separately. Please wait before merging and I'll add it to the README.

**Comment by zzamboni** [comment]
I've added documentation and an example, feel free to merge as you wish.

**Comment by nickanderson** [comment]
Last question. Instead of wrap in main, run with main?

**Comment by zzamboni** [comment]
Done.

**Comment by zzamboni** [comment]
@nickanderson please wait (again) before you merge - I think I figured out a way to allow expanding the body before tangling as well. What do you think - should this be controlled by a separate option for tangle? E.g. `:run-with-main` for execution, `:tangle-with-main` for tangling. And maybe `:auto-main` to enable both?

**Comment by zzamboni** [comment]
OK, new options implemented. Turned out to be easier than I thought. Please let me know what you think.

**Comment by nickanderson** [comment]
```
:auto-main is a shortcut for enabling both :tangle-with-main and
:run-with-main.
```

This was going to be my next suggestion!

I like it. I will let it sit and percolate for just a bit.

**Comment by nickanderson** [comment]
I was thinking about the difference between `__main__` and `main`.

If both appear in the same file, under the current implementation there will be an error. I am a bit unsure which one is better to use for the standalone examples.

**Comment by nickanderson** [comment]
The benefit of using `__main__` for tangled files, is that those tangled files could be included in a larger policy set without conflict. But, if all implementation exists within `__main__` then it would only be useful for direct execution. I guess for incomplete snippets, only direct execution makes sense.

**Comment by zzamboni** [comment]
That's why I chose `__main__` by default, because then every file could have its own and still be usable from others. Ultimately I think this is just a convenience - for any more complex cases, the author should include the complete code to avoid confusion. Of course, for people who want to use another bundle name, the template can be customized.

**Comment by zzamboni** [comment]
The latest commit 07cad67 introduces some changes not strictly related to this PR, particularly using the :tangle filename as default value for :command-in-result-filename. Apologies for mixing these, hope this is OK but please let me know if you want me to split them off into a separate PR.

**Comment by zzamboni** [comment]
Thanks!

**Pull request merged**
