### PR TITLE
New options for specifying command and display per block

### PR DESCRIPTION
**Pull request by zzamboni**
New header options accepted by ob-cfengine3 source blocks:

- `:command` to specify the command to use to executed the code block. The specified command must accept the same options as  `cf-agent`. Defaults to the value of `ob-cfengine3-command`.
- `:command-in-result` if set to `yes`, include the command in the  output, with all the options used, plus any modifications specified  by the following options.
- `:command-in-result-prompt` specifies the prompt to use when  `:command-in-result` is used. Default "# ".
- `:command-in-result-command` specifies which command to show in the  output instead of the real one. Defaults to the value of `:command`.
- `:command-in-result-filename` specifies a filename to show in the  output instead of the real one. Defaults to the temp filename  computed internally to store the code block.

### CODE REVIEW

**Comment by nickanderson** [comment]
Cool! This works in my testing. I would like to add some examples into the README to show how to use them.

Before I do so, is there a specific reason that you chose not to use `ob-cfengine3-` prefixed header arguments instead of `command-`? I am still an emacs neophyte so I don't know what's considered /right/.

I see you folowed my convention of `yes` to enable. Unrelated to this change, should I be looking to change those to not nil?

**Comment by nickanderson** [comment]
Did you see my question above?

**Comment by zzamboni** [comment]
Yes, just been very busy. Will  try to reply later today :)

**Comment by zzamboni** [comment]
@nickanderson about the argument names: I am not an expert by any means, but most (all?) org-babel modules I have seen use header arguments without the prefix in the module names. The prefix seems to be commonly used for configuration variables and function names, but I guess the idea of header arguments is to make them readable. Some examples:

`ob-C`: https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-C.html#org62938b5
`ob-dot`: https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-dot.html#orgc0b1fc3 (note the use of `cmd` in this one, maybe we use this instead of `command`?)
`latex`: https://orgmode.org/worg/org-contrib/babel/languages/ob-doc-LaTeX.html#org0e0e772

Ultimately is your module, so I'll agree to whatever naming convention you want :)

About the boolean arguments: actually I think the code already acts on "not nil" despite what the documentation says. For example:

**Update**: note my last commit below, which changes this behavior.

```emacs-lisp
(info (cdr (assoc :info params)))
...
(when info (concat "--inform "))
```
(btw I just realized this is a useless use of `concat`, will remove it and similar others on the next update)

So no matter what the value given to the parameter is, it will be considered as true.

Let me know what you think about the arg names, and I'll update the PR. I'll also add some examples to the README.

Thanks!

**Comment by nickanderson** [comment]
Ok and also new version have a log-level option. That could be used instead of having two options. Just FYI.

**Comment by nickanderson** [comment]
I'm fine with these options, can you update the readme with examples and bump the version?

**Comment by zzamboni** [comment]
I've added some examples in the README, also cleaned up the code a bit (spacing and ordering mainly).

**Comment by nickanderson** [comment]
Thanks! I did go ahead and standardize the readme on use of t for yes/true as well.

**Comment by zzamboni** [comment]
Awesome! I was thinking of accepting `t` as well, glad you thought the same :)

**Pull request merged**
